### PR TITLE
Feat: add data writer

### PR DESCRIPTION
**Pull request by mike-audi**
Adds lambda function to aggregate staged data and write to lake.

### CODE REVIEW

**Comment by mike-audi** [comment]
MISSING:

- SQS NOTIFICATION
- INTEGRATION TESTING

NICE TO HAVES:
- MOCKED UNIT TESTS
- FILTER ON EVENTS TO LIMIT FUNCTION TO SINGLE TABLE WRITES (BETTER FOR ERROR HANDLING)

**Comment by timoguin** [comment]
So we're writing the data in Avro for this first pass?

**Comment by mike-audi** [comment]
> So we're writing the data in Avro for this first pass?

Is it significantly more performant to be using parquet? If so it should be a very easy change. 

Assuming this (or similar) works: https://javadoc.io/doc/org.apache.parquet/parquet-avro/latest/org/apache/parquet/avro/package-summary.html

**Comment by timoguin** [comment]
> > So we're writing the data in Avro for this first pass?
> 
> Is it significantly more performant to be using parquet? If so it should be a very easy change.
> 
> Assuming this (or similar) works: https://javadoc.io/doc/org.apache.parquet/parquet-avro/latest/org/apache/parquet/avro/package-summary.html

I haven't seen any real benchmarks, but I'd assume columnar formats in general are going to be much more performant.

**Comment by timoguin** [comment]
Here are some results I found from a quick search:

- https://medium.com/ssense-tech/csv-vs-parquet-vs-avro-choosing-the-right-tool-for-the-right-job-79c9f56914a8
- https://www.slideshare.net/HadoopSummit/file-format-benchmark-avro-json-orc-and-parquet
- https://towardsdatascience.com/data-lake-comparing-performance-of-known-big-data-formats-eace705b6fd8
- https://stackoverflow.com/questions/53571888/spark-avro-vs-parquet-performance

Generally I think we will probably get better compression from Parquet, and queries are almost certainly going to be faster (especially if we are selecting specific columns and/or performing aggregate queries).

**Pull request merged**
